[package]
name = "liquislime-slime-clicker-plugin"
version = "0.1.0"
authors = ["kajacx"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "liquislime:slime-clicker"

[dependencies]
wit-bindgen = { version = "0.15.0" }
derive_more = { version = "0.99.17" }
