[package]
name = "liquislime-slime-spawner-plugin"
version = "0.1.0"
authors = ["kajacx"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
# liquislime-api = { path = "../../liquislime-rust-api" }
wit-bindgen = "*"
