[package]
name = "liquislime-user-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "liquislime:user-plugin"

[dependencies]
liquislime-api = { path = "../liquislime-rust-api" }
