version: "3.7"

services:
  liquislime-webserver:
    image: nginx:latest
    container_name: liquislime-webserver
    ports:
      - "8088:80"
    volumes:
      - ..:/usr/share/nginx/html
    restart: unless-stopped
