[package]
name = "liquislime-wasmi"
description = "A wasmi implementation for wasm in LiquiSlime"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
liquislime-core = { path = "../liquislime-core" }
wasmi-component = { path = "../../../../wasmi-component/crates/wasmi-component" }
wasmi-component-wasi = { path = "../../../../wasmi-component/crates/wasmi-component-wasi" }
