[package]
name = "liquislime-settings"
version = "0.1.0"
authors = ["kajacx"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.85" }
quote = { version = "1.0.36" }
syn = { version = "2.0.66", features = ["extra-traits", "full"] }
