[package]
name = "liquislime-slime-voider-plugin"
version = "0.1.0"
authors = ["kajacx"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "liquislime:slime-voider"

[dependencies]
liquislime-api = { path = "../../liquislime-rust-api" }
